# Generated by Django 2.2.6 on 2020-04-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='user',
        ),
    ]
