# Generated by Django 2.2.6 on 2020-04-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_post',
        ),
        migrations.AddField(
            model_name='profile',
            name='decsriprion',
            field=models.TextField(default='i am very good person', max_length=500),
        ),
    ]
