# Generated by Django 2.2.6 on 2020-04-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20200407_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
