# Generated by Django 2.2.6 on 2020-04-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='decsriprion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
