# Generated by Django 2.2.6 on 2020-04-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20200408_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
