# Generated by Django 2.2.6 on 2020-04-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20200408_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default='profilepictures/profile.png', upload_to='profilepictures'),
        ),
    ]
